import Footer from "./Footer";
import "./globals.css";
import Header from "./Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="overflow-hidden bg-stone-200 p-1 py-4 font-grotesk dark:bg-gray-900 sm:px-3">
        <Header />
        <div
          id="polka"
          className="rounded-xl border-2 border-black bg-stone-100 px-5 py-6 text-black dark:border dark:border-gray-300 dark:bg-gray-800 dark:text-gray-300"
        >
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
